services:
  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mantenedor_db
      POSTGRES_USER: mantenedor_user
      POSTGRES_PASSWORD: mantenedor_pass
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    # CORRECCIÓN: Se añade 'brokernuam/' a las rutas de manage.py
    command: >
      sh -c "python brokernuam/manage.py migrate &&
             python brokernuam/manage.py collectstatic --noinput &&
             gunicorn brokernuam.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: brokernuam.settings
      DATABASE_URL: postgres://mantenedor_user:mantenedor_pass@db:5432/mantenedor_db
      DEBUG: 'False'
      SECRET_KEY: your-prod-secret-key
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://backend:8000/api/
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:1.21
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # CORRECCIÓN: Asumiendo que tu frontend build está en ./frontend/build
      # Si no, ajusta esta ruta
      - ./frontend/build:/usr/share/nginx/html 
    ports:
      - "80:80"

volumes:
  db_data: