services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    env_file: .env  # <--- IMPORTANTE: Lee las variables del archivo
    networks:
      - nuam_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - nuam_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - nuam_network

  srv-django-backend:
    build: ./srv-django-backend
    container_name: nuam_backend
    restart: unless-stopped
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file /app/certs/cert.pem --key-file /app/certs/key.pem
    volumes:
      - ./srv-django-backend:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092 # <--- Necesario para que Django vea a Kafka
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
    networks:
      - nuam_network
    depends_on:
      - postgres
      - kafka

  srv-kafka-consumer:
    build: ./srv-kafka-consumer
    container_name: nuam_consumer
    restart: unless-stopped
    env_file: .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
      - PYTHONPATH=/app/backend  
    volumes:
      - ./srv-kafka-consumer:/app
      - ./srv-django-backend:/app/backend
    networks:
      - nuam_network
    depends_on:
      - kafka
      - postgres
      - srv-django-backend
  
  srv-notifier:
    build: ./srv-notifier
    container_name: nuam_notifier
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - nuam_network
    depends_on:
      - kafka

networks:
  nuam_network:
    driver: bridge

volumes:
  postgres_data: