services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mantenedor_db
      POSTGRES_USER: mantenedor_user
      POSTGRES_PASSWORD: mantenedor_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mantenedor_user -d mantenedor_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    # CORRECCIÃ“N:
    # 1. Usar la ruta 'brokernuam/manage.py' (basado en tu error de permisos anterior).
    # 2. Decirle a Gunicorn que cambie al directorio '/app/brokernuam' ANTES de buscar el wsgi.
    command: >
      sh -c "python brokernuam/manage.py migrate &&
             gunicorn --chdir /app/brokernuam brokernuam.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: brokernuam.settings
      DATABASE_URL: postgres://mantenedor_user:mantenedor_pass@db:5432/mantenedor_db
      DEBUG: 'False'
      SECRET_KEY: your-prod-secret-key
    volumes:
      - ./backend:/app
      - static_data:/app/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://backend:8000/api/
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:1.21
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/app/static:ro
    ports:
      - "80:80"

volumes:
  db_data:
  static_data: